/* The following code was generated by JFlex 1.7.0 */

package org.example.lexer;

import java.util.ArrayList;
import java.util.List;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/main/java/org/example/lexer/Lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int BLOCK_COMMENT = 2;
  public static final int STRING_DQ = 4;
  public static final int STRING_SQ = 6;
  public static final int IDENT_STATE = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\6\1\72\1\72\1\71\22\0\1\4\1\0\1\66"+
    "\4\0\1\67\2\0\1\7\3\0\1\3\1\5\12\2\7\0\1\53"+
    "\1\57\1\45\1\52\1\40\1\64\1\37\1\62\1\60\1\65\1\1"+
    "\1\42\1\41\1\63\1\43\1\56\1\1\1\46\1\44\1\55\1\47"+
    "\1\61\2\1\1\54\1\50\1\0\1\70\2\0\1\51\1\0\1\15"+
    "\1\33\1\10\1\31\1\14\1\35\1\30\1\11\1\20\1\32\1\1"+
    "\1\27\1\21\1\22\1\12\1\23\1\36\1\16\1\17\1\13\1\24"+
    "\1\26\1\25\2\1\1\34\12\0\1\72\72\0\3\1\1\0\1\1"+
    "\3\0\10\1\1\0\4\1\1\0\1\1\2\0\4\1\3\0\3\1"+
    "\1\0\1\1\3\0\10\1\1\0\4\1\1\0\1\1\2\0\4\1"+
    "\u1f2b\0\1\72\1\72\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\3\1\4\1\1\32\2\1\5"+
    "\1\6\2\7\1\10\1\11\1\12\1\0\1\10\1\13"+
    "\1\14\1\0\1\15\1\10\1\0\1\4\1\16\54\0"+
    "\1\17\1\10\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\17\0\1\27\4\0\1\30\25\0\1\31\37\0"+
    "\1\32\3\0\1\33\2\0\1\34\3\0\1\35\2\0"+
    "\1\36\5\0\1\37\1\40\1\0\1\41\3\0\1\42"+
    "\1\43\1\44\1\45\12\0\1\46\1\0\1\47\3\0"+
    "\1\50\4\0\1\51\1\0\1\52\3\0\1\53\1\0"+
    "\1\54\2\0\1\55\3\0\1\56\1\0\1\57\2\0"+
    "\1\60\1\0\1\61\1\0\1\62\1\0\1\63\1\64"+
    "\1\0\1\65\1\0\1\66\1\67\4\0\1\70\1\0"+
    "\1\71\2\0\1\72\1\0\1\73\6\0\1\74\1\75"+
    "\5\0\1\76\1\77\1\100\1\101\1\102\1\103\2\0"+
    "\1\104\2\0\1\105\1\106\1\107\1\0\1\110\10\0"+
    "\1\111\1\112\2\0\1\113\2\0\1\114\1\115\2\0"+
    "\1\116\1\117\1\120\2\0\1\121\1\122\1\123\1\124"+
    "\1\125\2\0\1\126";

  private static int [] zzUnpackAction() {
    int [] result = new int[338];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0127\0\u0162"+
    "\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\u02ff\0\u033a"+
    "\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7\0\u0512"+
    "\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\u0674\0\u06af\0\u06ea"+
    "\0\u0725\0\u0760\0\u079b\0\u07d6\0\u0127\0\u0127\0\u0127\0\u0811"+
    "\0\u084c\0\u0127\0\u0127\0\u0887\0\u08c2\0\u0127\0\u0127\0\u08fd"+
    "\0\u0127\0\u0938\0\u0973\0\u09ae\0\u0127\0\u09e9\0\u0a24\0\u0a5f"+
    "\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37"+
    "\0\u0c72\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f"+
    "\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u0f36\0\u0f71\0\u0fac\0\u0fe7"+
    "\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184\0\u11bf"+
    "\0\u11fa\0\u1235\0\u1270\0\u12ab\0\u12e6\0\u1321\0\u135c\0\u1397"+
    "\0\u13d2\0\u0127\0\u0127\0\u0127\0\u0127\0\u0127\0\u0127\0\u0127"+
    "\0\u0127\0\u0973\0\u140d\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534"+
    "\0\u156f\0\u15aa\0\u15e5\0\u1620\0\u165b\0\u1696\0\u16d1\0\u170c"+
    "\0\u1747\0\u0127\0\u1782\0\u17bd\0\u17f8\0\u1833\0\u0127\0\u186e"+
    "\0\u18a9\0\u18e4\0\u191f\0\u195a\0\u1995\0\u19d0\0\u1a0b\0\u1a46"+
    "\0\u1a81\0\u1abc\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e"+
    "\0\u1c59\0\u1c94\0\u1ccf\0\u1d0a\0\u0127\0\u1d45\0\u1d80\0\u1dbb"+
    "\0\u1df6\0\u1e31\0\u1e6c\0\u1ea7\0\u1ee2\0\u1f1d\0\u1f58\0\u1f93"+
    "\0\u1fce\0\u2009\0\u2044\0\u207f\0\u20ba\0\u20f5\0\u2130\0\u216b"+
    "\0\u21a6\0\u21e1\0\u221c\0\u2257\0\u2292\0\u22cd\0\u2308\0\u2343"+
    "\0\u237e\0\u23b9\0\u23f4\0\u242f\0\u0127\0\u246a\0\u24a5\0\u24e0"+
    "\0\u0127\0\u251b\0\u2556\0\u0127\0\u2591\0\u25cc\0\u2607\0\u0127"+
    "\0\u2642\0\u267d\0\u26b8\0\u26f3\0\u272e\0\u2769\0\u27a4\0\u27df"+
    "\0\u281a\0\u0127\0\u2855\0\u0127\0\u2890\0\u28cb\0\u2906\0\u0127"+
    "\0\u0127\0\u0127\0\u0127\0\u2941\0\u297c\0\u29b7\0\u29f2\0\u2a2d"+
    "\0\u2a68\0\u2aa3\0\u2ade\0\u2b19\0\u2b54\0\u0127\0\u2b8f\0\u0127"+
    "\0\u2bca\0\u2c05\0\u2c40\0\u0127\0\u2c7b\0\u2cb6\0\u2cf1\0\u2d2c"+
    "\0\u0127\0\u2d67\0\u0127\0\u2da2\0\u2ddd\0\u2e18\0\u0127\0\u2e53"+
    "\0\u0127\0\u2e8e\0\u2ec9\0\u2f04\0\u2f3f\0\u2f7a\0\u2fb5\0\u0127"+
    "\0\u2ff0\0\u302b\0\u3066\0\u30a1\0\u0127\0\u30dc\0\u0127\0\u3117"+
    "\0\u0127\0\u3152\0\u0127\0\u0127\0\u318d\0\u0127\0\u31c8\0\u0127"+
    "\0\u0127\0\u3203\0\u323e\0\u3279\0\u32b4\0\u0127\0\u32ef\0\u0127"+
    "\0\u332a\0\u3365\0\u0127\0\u33a0\0\u0127\0\u33db\0\u3416\0\u3451"+
    "\0\u348c\0\u34c7\0\u3502\0\u0127\0\u0127\0\u353d\0\u3578\0\u35b3"+
    "\0\u35ee\0\u3629\0\u0127\0\u0127\0\u0127\0\u0127\0\u0127\0\u0127"+
    "\0\u3664\0\u369f\0\u0127\0\u36da\0\u3715\0\u0127\0\u0127\0\u0127"+
    "\0\u3750\0\u0127\0\u378b\0\u37c6\0\u3801\0\u383c\0\u3877\0\u38b2"+
    "\0\u38ed\0\u3928\0\u0127\0\u0127\0\u3963\0\u399e\0\u39d9\0\u3a14"+
    "\0\u3a4f\0\u0127\0\u0127\0\u3a8a\0\u3ac5\0\u0127\0\u0127\0\u0127"+
    "\0\u3b00\0\u3b3b\0\u0127\0\u0127\0\u0127\0\u0127\0\u0127\0\u3b76"+
    "\0\u3bb1\0\u0127";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[338];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\6\1\11\1\12\1\11\1\6"+
    "\1\13\3\7\1\14\1\15\1\7\1\16\1\17\1\20"+
    "\1\21\1\22\1\7\1\23\1\24\2\7\1\25\1\7"+
    "\1\26\1\7\1\27\1\7\1\30\1\31\2\7\1\32"+
    "\1\33\1\34\1\35\3\7\1\36\1\37\1\7\1\40"+
    "\1\41\1\42\1\7\1\43\2\7\1\44\1\7\1\45"+
    "\1\46\1\6\1\11\1\6\7\47\1\50\63\47\6\51"+
    "\1\52\57\51\1\53\1\51\1\54\2\51\6\55\1\56"+
    "\60\55\1\57\1\60\2\55\1\61\2\62\5\61\56\62"+
    "\5\61\75\0\1\10\1\63\73\0\1\11\1\0\1\11"+
    "\62\0\1\11\6\0\1\64\1\0\1\65\74\0\1\66"+
    "\3\0\1\67\6\0\1\70\65\0\1\71\66\0\1\72"+
    "\73\0\1\73\3\0\1\74\74\0\1\75\62\0\1\76"+
    "\74\0\1\77\3\0\1\100\64\0\1\101\5\0\1\102"+
    "\67\0\1\103\67\0\1\104\11\0\1\105\62\0\1\106"+
    "\1\107\72\0\1\110\75\0\1\111\112\0\1\112\5\0"+
    "\1\113\70\0\1\114\113\0\1\115\45\0\1\116\2\0"+
    "\1\117\75\0\1\120\1\121\3\0\1\122\57\0\1\123"+
    "\12\0\1\124\66\0\1\125\3\0\1\126\4\0\1\127"+
    "\54\0\1\130\12\0\1\131\1\0\1\132\53\0\1\133"+
    "\12\0\1\134\77\0\1\135\55\0\1\136\7\0\1\137"+
    "\72\0\1\140\65\0\1\141\31\0\1\142\65\0\6\51"+
    "\1\0\57\51\1\0\1\51\1\0\2\51\6\143\1\0"+
    "\4\143\1\144\2\143\1\145\3\143\1\146\43\143\1\147"+
    "\1\143\1\150\2\0\6\55\1\0\60\55\2\0\2\55"+
    "\6\143\1\0\4\143\1\144\2\143\1\145\3\143\1\146"+
    "\44\143\1\151\1\150\3\0\2\62\5\0\56\62\7\0"+
    "\1\152\70\0\6\64\1\0\64\64\12\0\1\153\2\0"+
    "\1\154\2\0\1\155\62\0\1\156\6\0\1\157\7\0"+
    "\1\160\3\0\1\161\2\0\1\162\51\0\1\163\70\0"+
    "\1\164\75\0\1\165\104\0\1\166\63\0\1\167\75\0"+
    "\1\170\64\0\1\171\103\0\1\172\64\0\1\173\67\0"+
    "\1\174\73\0\1\175\72\0\1\176\72\0\1\177\2\0"+
    "\1\200\64\0\1\201\101\0\1\202\76\0\1\203\61\0"+
    "\1\204\3\0\1\205\102\0\1\206\101\0\1\207\111\0"+
    "\1\210\67\0\1\211\60\0\1\212\70\0\1\213\110\0"+
    "\1\214\62\0\1\215\63\0\1\216\104\0\1\217\12\0"+
    "\1\220\51\0\1\221\67\0\1\222\12\0\1\223\70\0"+
    "\1\224\66\0\1\225\105\0\1\226\52\0\1\227\74\0"+
    "\1\230\75\0\1\231\71\0\1\232\103\0\1\233\61\0"+
    "\1\234\72\0\1\235\71\0\1\236\70\0\1\237\70\0"+
    "\1\240\45\0\1\241\101\0\1\242\1\243\65\0\1\244"+
    "\1\245\64\0\1\246\76\0\1\247\72\0\1\250\72\0"+
    "\1\251\101\0\1\252\100\0\1\253\56\0\1\254\71\0"+
    "\1\255\101\0\1\256\60\0\1\257\73\0\1\260\71\0"+
    "\1\261\75\0\1\262\74\0\1\263\66\0\1\264\74\0"+
    "\1\265\67\0\1\266\107\0\1\267\72\0\1\270\57\0"+
    "\1\271\74\0\1\272\105\0\1\273\53\0\1\274\120\0"+
    "\1\275\107\0\1\276\63\0\1\277\70\0\1\300\106\0"+
    "\1\301\60\0\1\302\74\0\1\303\70\0\1\304\64\0"+
    "\1\305\75\0\1\306\105\0\1\307\72\0\1\310\67\0"+
    "\1\311\72\0\1\312\62\0\1\313\102\0\1\314\60\0"+
    "\1\315\104\0\1\316\101\0\1\317\63\0\1\320\62\0"+
    "\1\321\102\0\1\322\57\0\1\323\74\0\1\324\113\0"+
    "\1\325\23\0\1\326\76\0\1\327\76\0\1\330\66\0"+
    "\1\331\73\0\1\332\71\0\1\333\62\0\1\334\111\0"+
    "\1\335\72\0\1\336\57\0\1\337\72\0\1\340\72\0"+
    "\1\341\101\0\1\342\67\0\1\343\74\0\1\344\70\0"+
    "\1\345\74\0\1\346\70\0\1\347\72\0\1\350\64\0"+
    "\1\351\2\0\1\352\74\0\1\353\66\0\1\354\74\0"+
    "\1\355\75\0\1\356\67\0\1\357\117\0\1\360\73\0"+
    "\1\361\67\0\1\362\74\0\1\363\103\0\1\364\70\0"+
    "\1\365\77\0\1\366\77\0\1\367\72\0\1\370\62\0"+
    "\1\371\72\0\1\372\70\0\1\373\67\0\1\374\67\0"+
    "\1\375\77\0\1\376\65\0\1\377\102\0\1\u0100\62\0"+
    "\1\u0101\44\0\1\u0102\77\0\1\u0103\67\0\1\u0104\76\0"+
    "\1\u0105\63\0\1\u0106\71\0\1\u0107\74\0\1\u0108\71\0"+
    "\1\u0109\74\0\1\u010a\76\0\1\u010b\65\0\1\u010c\104\0"+
    "\1\u010d\72\0\1\u010e\73\0\1\u010f\61\0\1\u0110\70\0"+
    "\1\u0111\111\0\1\u0112\53\0\1\u0113\77\0\1\u0114\62\0"+
    "\1\u0115\123\0\1\u0116\71\0\1\u0117\72\0\1\u0118\101\0"+
    "\1\u0119\66\0\1\u011a\4\0\1\u011b\63\0\1\u011c\102\0"+
    "\1\u011d\61\0\1\u011e\101\0\1\u011f\67\0\1\u0120\3\0"+
    "\1\u0121\65\0\1\u0122\70\0\1\u0123\73\0\1\u0124\44\0"+
    "\1\u0125\71\0\1\u0126\67\0\1\u0127\72\0\1\u0128\75\0"+
    "\1\u0129\104\0\1\u012a\57\0\1\u012b\73\0\1\u012c\65\0"+
    "\1\u012d\74\0\1\u012e\72\0\1\u012f\124\0\1\u0130\70\0"+
    "\1\u0131\103\0\1\u0132\71\0\1\u0133\66\0\1\u0134\77\0"+
    "\1\u0135\71\0\1\u0136\72\0\1\u0137\73\0\1\u0138\72\0"+
    "\1\u0139\77\0\1\u013a\30\0\1\u013b\66\0\1\u013c\114\0"+
    "\1\u013d\53\0\1\u013e\130\0\1\u013f\72\0\1\u0140\66\0"+
    "\1\u0141\71\0\1\u0142\67\0\1\u0143\102\0\1\u0144\73\0"+
    "\1\u0145\64\0\1\u0146\67\0\1\u0147\41\0\1\u0148\77\0"+
    "\1\u0149\124\0\1\u014a\67\0\1\u014b\74\0\1\u014c\70\0"+
    "\1\u014d\77\0\1\u014e\31\0\1\u014f\132\0\1\u0150\73\0"+
    "\1\u0151\65\0\1\u0152\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15340];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\2\11\35\1\3\11\2\1\2\11\1\0\1\1"+
    "\2\11\1\0\1\11\1\1\1\0\1\1\1\11\54\0"+
    "\10\11\1\1\17\0\1\11\4\0\1\11\25\0\1\11"+
    "\37\0\1\11\3\0\1\11\2\0\1\11\3\0\1\11"+
    "\2\0\1\1\5\0\1\1\1\11\1\0\1\11\3\0"+
    "\4\11\12\0\1\11\1\0\1\11\3\0\1\11\4\0"+
    "\1\11\1\0\1\11\3\0\1\11\1\0\1\11\2\0"+
    "\1\1\3\0\1\11\1\0\1\1\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\1\0\2\11\1\0\1\11\1\0"+
    "\2\11\4\0\1\11\1\0\1\11\2\0\1\11\1\0"+
    "\1\11\6\0\2\11\5\0\6\11\2\0\1\11\2\0"+
    "\3\11\1\0\1\11\10\0\2\11\2\0\1\1\2\0"+
    "\2\11\2\0\3\11\2\0\5\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[338];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private final List<LexicalError> errors = new ArrayList<>();

    public List<LexicalError> getErrors() {
        return errors;
    }

    private Token token(TokenType type) {
        return new Token(yytext(), type, yyline + 1, yycolumn + 1);
    }

    private Token token(TokenType type, String value) {
        return new Token(value, type, yyline + 1, yycolumn + 1);
    }

    private void lexicalError(String message) {
        errors.add(new LexicalError(
            yytext(),
            message,
            yyline + 1,
            yycolumn + 1
        ));
    }

    private int errorLine;
    private int errorColumn;
    private StringBuilder stringBuffer = new StringBuilder();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 240) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              return token(TokenType.EOF);
            }  // fall though
            case 339: break;
            case BLOCK_COMMENT: {
              errors.add(new LexicalError(
                    "/*",
                    "Comentario de bloque no cerrado",
                    errorLine,
                    errorColumn
                ));
                return token(TokenType.EOF);
            }  // fall though
            case 340: break;
            case STRING_DQ: {
              errors.add(new LexicalError(
                     "\"" + stringBuffer.toString(),
                     "Cadena de texto no cerrada (fin de archivo)",
                     errorLine, errorColumn
                 ));
                 return token(TokenType.EOF);
            }  // fall though
            case 341: break;
            case STRING_SQ: {
              errors.add(new LexicalError(
                     "'" + stringBuffer.toString(),
                     "Cadena de texto no cerrada (fin de archivo)",
                     errorLine, errorColumn
                 ));
                 return token(TokenType.EOF);
            }  // fall though
            case 342: break;
            case IDENT_STATE: {
              yybegin(YYINITIAL);
                String lexema = stringBuffer.toString();
                boolean tieneInvalido = false;
                for (int cp, i = 0; i < lexema.length(); i += Character.charCount(cp)) {
                    cp = lexema.codePointAt(i);
                    if (cp > 127) { tieneInvalido = true; break; }
                }
                if (tieneInvalido) {
                    errors.add(new LexicalError(
                        lexema,
                        "Identificador inválido: '" + lexema +
                        "' — no se permiten tildes ni la letra ñ",
                        errorLine,
                        errorColumn
                    ));
                } else {
                    return new Token(lexema, TokenType.IDENTIFIER, errorLine, errorColumn);
                }
                return token(TokenType.EOF);
            }  // fall though
            case 343: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexicalError("Símbolo no reconocido: '" + yytext() + "'");
            } 
            // fall through
          case 87: break;
          case 2: 
            { stringBuffer.setLength(0);
        stringBuffer.append(yytext());
        errorLine   = yyline + 1;
        errorColumn = yycolumn + 1;
        yybegin(IDENT_STATE);
            } 
            // fall through
          case 88: break;
          case 3: 
            { return token(TokenType.INTEGER_LITERAL);
            } 
            // fall through
          case 89: break;
          case 4: 
            { /* ignorar */
            } 
            // fall through
          case 90: break;
          case 5: 
            { stringBuffer.setLength(0);
           errorLine   = yyline + 1;
           errorColumn = yycolumn + 1;
           yybegin(STRING_DQ);
            } 
            // fall through
          case 91: break;
          case 6: 
            { stringBuffer.setLength(0);
           errorLine   = yyline + 1;
           errorColumn = yycolumn + 1;
           yybegin(STRING_SQ);
            } 
            // fall through
          case 92: break;
          case 7: 
            { // consumir cualquier carácter, incluidas tildes
            } 
            // fall through
          case 93: break;
          case 8: 
            { stringBuffer.append(yytext());
            } 
            // fall through
          case 94: break;
          case 9: 
            { errors.add(new LexicalError(
                     "\"" + stringBuffer.toString(),
                     "Cadena de texto no cerrada (salto de línea inesperado)",
                     errorLine, errorColumn
                 ));
                 yybegin(YYINITIAL);
            } 
            // fall through
          case 95: break;
          case 10: 
            { yybegin(YYINITIAL);
                 return token(TokenType.STRING_LITERAL,
                              "\"" + stringBuffer.toString() + "\"");
            } 
            // fall through
          case 96: break;
          case 11: 
            { errors.add(new LexicalError(
                     "'" + stringBuffer.toString(),
                     "Cadena de texto no cerrada (salto de línea inesperado)",
                     errorLine, errorColumn
                 ));
                 yybegin(YYINITIAL);
            } 
            // fall through
          case 97: break;
          case 12: 
            { yybegin(YYINITIAL);
                 String content = stringBuffer.toString();
                 boolean isEscape = content.length() == 2 && content.charAt(0) == '\\';
                 boolean isSingle = content.codePointCount(0, content.length()) == 1;
                 if (isEscape || isSingle) {
                     return token(TokenType.CHAR_LITERAL, "'" + content + "'");
                 }
                 return token(TokenType.STRING_LITERAL, "\"" + content + "\"");
            } 
            // fall through
          case 98: break;
          case 13: 
            { yypushback(1);
            yybegin(YYINITIAL);

            String lexema = stringBuffer.toString();

            // Comprobar si contiene algún carácter acentuado o ñ
            boolean tieneInvalido = false;
            for (int cp, i = 0; i < lexema.length(); i += Character.charCount(cp)) {
                cp = lexema.codePointAt(i);
                // Rango aproximado de letras latinas con diacríticos
                if (cp > 127) { tieneInvalido = true; break; }
            }

            if (tieneInvalido) {
                errors.add(new LexicalError(
                    lexema,
                    "Identificador inválido: '" + lexema +
                    "' — no se permiten tildes ni la letra ñ",
                    errorLine,
                    errorColumn
                ));
                // No retorna token — el parser nunca ve este lexema
            } else {
                // Lexema ASCII puro → token IDENTIFIER
                // (las palabras reservadas ya fueron capturadas antes de
                //  entrar al estado, por lo que aquí solo llegan ids normales)
                return new Token(lexema, TokenType.IDENTIFIER, errorLine, errorColumn);
            }
            } 
            // fall through
          case 99: break;
          case 14: 
            { errorLine   = yyline + 1;
             errorColumn = yycolumn + 1;
             yybegin(BLOCK_COMMENT);
            } 
            // fall through
          case 100: break;
          case 15: 
            { yybegin(YYINITIAL);
            } 
            // fall through
          case 101: break;
          case 16: 
            { stringBuffer.append("\\t");
            } 
            // fall through
          case 102: break;
          case 17: 
            { stringBuffer.append("\\r");
            } 
            // fall through
          case 103: break;
          case 18: 
            { stringBuffer.append("\\n");
            } 
            // fall through
          case 104: break;
          case 19: 
            { stringBuffer.append("\\\"");
            } 
            // fall through
          case 105: break;
          case 20: 
            { stringBuffer.append("\\\\");
            } 
            // fall through
          case 106: break;
          case 21: 
            { stringBuffer.append("\\'");
            } 
            // fall through
          case 107: break;
          case 22: 
            { return token(TokenType.DECIMAL_LITERAL);
            } 
            // fall through
          case 108: break;
          case 23: 
            { return token(TokenType.FALSE);
            } 
            // fall through
          case 109: break;
          case 24: 
            { return token(TokenType.THIS);
            } 
            // fall through
          case 110: break;
          case 25: 
            { return token(TokenType.ASSIGN);
            } 
            // fall through
          case 111: break;
          case 26: 
            { return token(TokenType.CASE);
            } 
            // fall through
          case 112: break;
          case 27: 
            { return token(TokenType.DO);
            } 
            // fall through
          case 113: break;
          case 28: 
            { return token(TokenType.CONST);
            } 
            // fall through
          case 114: break;
          case 29: 
            { return token(TokenType.COLON);
            } 
            // fall through
          case 115: break;
          case 30: 
            { return token(TokenType.PLUS);
            } 
            // fall through
          case 116: break;
          case 31: 
            { return token(TokenType.MINUS);
            } 
            // fall through
          case 117: break;
          case 32: 
            { return token(TokenType.QUESTION);
            } 
            // fall through
          case 118: break;
          case 33: 
            { return token(TokenType.LEFT_BRACE);
            } 
            // fall through
          case 119: break;
          case 34: 
            { return token(TokenType.RIGHT_BRACKET);
            } 
            // fall through
          case 120: break;
          case 35: 
            { return token(TokenType.LESS_THAN);
            } 
            // fall through
          case 121: break;
          case 36: 
            { return token(TokenType.GREATER_THAN);
            } 
            // fall through
          case 122: break;
          case 37: 
            { return token(TokenType.LESS_EQUAL);
            } 
            // fall through
          case 123: break;
          case 38: 
            { return token(TokenType.INT);
            } 
            // fall through
          case 124: break;
          case 39: 
            { return token(TokenType.BREAK);
            } 
            // fall through
          case 125: break;
          case 40: 
            { return token(TokenType.IF);
            } 
            // fall through
          case 126: break;
          case 41: 
            { return token(TokenType.FLOAT);
            } 
            // fall through
          case 127: break;
          case 42: 
            { return token(TokenType.RETURN);
            } 
            // fall through
          case 128: break;
          case 43: 
            { return token(TokenType.CLASS);
            } 
            // fall through
          case 129: break;
          case 44: 
            { return token(TokenType.NOT);
            } 
            // fall through
          case 130: break;
          case 45: 
            { return token(TokenType.MOD);
            } 
            // fall through
          case 131: break;
          case 46: 
            { return token(TokenType.LEFT_BRACKET);
            } 
            // fall through
          case 132: break;
          case 47: 
            { return token(TokenType.DIVIDE);
            } 
            // fall through
          case 133: break;
          case 48: 
            { return token(TokenType.DOT);
            } 
            // fall through
          case 134: break;
          case 49: 
            { return token(TokenType.GREATER_EQUAL);
            } 
            // fall through
          case 135: break;
          case 50: 
            { return token(TokenType.SEMICOLON);
            } 
            // fall through
          case 136: break;
          case 51: 
            { return token(TokenType.CONTINUE);
            } 
            // fall through
          case 137: break;
          case 52: 
            { return token(TokenType.ELSE);
            } 
            // fall through
          case 138: break;
          case 53: 
            { return token(TokenType.STRING);
            } 
            // fall through
          case 139: break;
          case 54: 
            { return token(TokenType.BOOL);
            } 
            // fall through
          case 140: break;
          case 55: 
            { return token(TokenType.TRY);
            } 
            // fall through
          case 141: break;
          case 56: 
            { return token(TokenType.NULL);
            } 
            // fall through
          case 142: break;
          case 57: 
            { return token(TokenType.VOID);
            } 
            // fall through
          case 143: break;
          case 58: 
            { return token(TokenType.FOR);
            } 
            // fall through
          case 144: break;
          case 59: 
            { return token(TokenType.PUBLIC);
            } 
            // fall through
          case 145: break;
          case 60: 
            { return token(TokenType.RIGHT_BRACE);
            } 
            // fall through
          case 146: break;
          case 61: 
            { return token(TokenType.AND);
            } 
            // fall through
          case 147: break;
          case 62: 
            { return token(TokenType.LEFT_PAREN);
            } 
            // fall through
          case 148: break;
          case 63: 
            { return token(TokenType.OR);
            } 
            // fall through
          case 149: break;
          case 64: 
            { return token(TokenType.PRINT);
            } 
            // fall through
          case 150: break;
          case 65: 
            { return token(TokenType.SWITCH);
            } 
            // fall through
          case 151: break;
          case 66: 
            { return token(TokenType.CHAR);
            } 
            // fall through
          case 152: break;
          case 67: 
            { return token(TokenType.PRIVATE);
            } 
            // fall through
          case 153: break;
          case 68: 
            { return token(TokenType.WHILE);
            } 
            // fall through
          case 154: break;
          case 69: 
            { return token(TokenType.DOUBLE);
            } 
            // fall through
          case 155: break;
          case 70: 
            { return token(TokenType.TRUE);
            } 
            // fall through
          case 156: break;
          case 71: 
            { return token(TokenType.EQUALS);
            } 
            // fall through
          case 157: break;
          case 72: 
            { return token(TokenType.COMMA);
            } 
            // fall through
          case 158: break;
          case 73: 
            { return token(TokenType.NEW);
            } 
            // fall through
          case 159: break;
          case 74: 
            { return token(TokenType.CATCH);
            } 
            // fall through
          case 160: break;
          case 75: 
            { return token(TokenType.MULTIPLY);
            } 
            // fall through
          case 161: break;
          case 76: 
            { return token(TokenType.PLUS_ASSIGN);
            } 
            // fall through
          case 162: break;
          case 77: 
            { return token(TokenType.RIGHT_PAREN);
            } 
            // fall through
          case 163: break;
          case 78: 
            { return token(TokenType.MINUS_ASSIGN);
            } 
            // fall through
          case 164: break;
          case 79: 
            { return token(TokenType.NOT_EQUALS);
            } 
            // fall through
          case 165: break;
          case 80: 
            { return token(TokenType.THROW);
            } 
            // fall through
          case 166: break;
          case 81: 
            { return token(TokenType.MOD_ASSIGN);
            } 
            // fall through
          case 167: break;
          case 82: 
            { return token(TokenType.INCREMENT);
            } 
            // fall through
          case 168: break;
          case 83: 
            { return token(TokenType.DIVIDE_ASSIGN);
            } 
            // fall through
          case 169: break;
          case 84: 
            { return token(TokenType.DECREMENT);
            } 
            // fall through
          case 170: break;
          case 85: 
            { return token(TokenType.DEFAULT);
            } 
            // fall through
          case 171: break;
          case 86: 
            { return token(TokenType.MULTIPLY_ASSIGN);
            } 
            // fall through
          case 172: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
