/* The following code was generated by JFlex 1.7.0 */

package org.example.lexer;

import java.util.ArrayList;
import java.util.List;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/main/java/org/example/lexer/Lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\10\1\12\1\12\1\11\22\0\1\5\1\0\1\6"+
    "\4\0\1\13\2\0\1\15\3\0\1\4\1\14\12\2\7\0\1\61"+
    "\1\65\1\53\1\60\1\46\1\72\1\45\1\70\1\66\1\73\1\1"+
    "\1\50\1\47\1\71\1\51\1\64\1\1\1\54\1\52\1\63\1\55"+
    "\1\67\2\1\1\62\1\56\1\0\1\7\2\0\1\57\1\0\1\23"+
    "\1\41\1\16\1\37\1\22\1\43\1\36\1\17\1\26\1\40\1\1"+
    "\1\35\1\27\1\30\1\20\1\31\1\44\1\24\1\25\1\21\1\32"+
    "\1\34\1\33\2\1\1\42\12\0\1\12\73\0\1\3\7\0\1\3"+
    "\3\0\1\3\3\0\1\3\1\0\1\3\6\0\1\3\6\0\1\3"+
    "\7\0\1\3\3\0\1\3\3\0\1\3\1\0\1\3\6\0\1\3"+
    "\u1f2d\0\1\12\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\3\1\32\2"+
    "\1\5\3\0\1\6\1\0\1\7\2\0\1\4\1\10"+
    "\54\2\1\11\1\10\17\2\1\12\4\2\1\13\25\2"+
    "\1\14\13\2\1\4\24\2\1\15\3\2\1\16\2\2"+
    "\1\17\3\2\1\20\2\2\1\21\5\2\1\22\1\23"+
    "\1\2\1\24\3\2\1\25\1\26\1\27\1\30\12\2"+
    "\1\31\1\2\1\32\3\2\1\33\4\2\1\34\1\2"+
    "\1\35\3\2\1\36\1\2\1\37\2\2\1\40\3\2"+
    "\1\41\1\2\1\42\2\2\1\43\1\2\1\44\1\2"+
    "\1\45\1\2\1\46\1\47\1\2\1\50\1\2\1\51"+
    "\1\52\4\2\1\53\1\2\1\54\2\2\1\55\1\2"+
    "\1\56\6\2\1\57\1\60\5\2\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\2\2\1\67\2\2\1\70\1\71"+
    "\1\72\1\2\1\73\10\2\1\74\1\75\2\2\1\76"+
    "\2\2\1\77\1\100\2\2\1\101\1\102\1\103\2\2"+
    "\1\104\1\105\1\106\1\107\1\110\2\2\1\111";

  private static int [] zzUnpackAction() {
    int [] result = new int[325];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\u012c\0\u0168\0\u01a4"+
    "\0\u01e0\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c\0\u0348\0\u0384"+
    "\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528\0\u0564"+
    "\0\u05a0\0\u05dc\0\u0618\0\u0654\0\u0690\0\u06cc\0\u0708\0\u0744"+
    "\0\u0780\0\u07bc\0\u07f8\0\u0834\0\u0870\0\360\0\u0168\0\74"+
    "\0\u08ac\0\74\0\u01a4\0\u08e8\0\u0924\0\u0960\0\u099c\0\u09d8"+
    "\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04\0\u0b40\0\u0b7c\0\u0bb8"+
    "\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4\0\u0d20\0\u0d5c\0\u0d98"+
    "\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4\0\u0f00\0\u0f3c\0\u0f78"+
    "\0\u0fb4\0\u0ff0\0\u102c\0\u1068\0\u10a4\0\u10e0\0\u111c\0\u1158"+
    "\0\u1194\0\u11d0\0\u120c\0\u1248\0\u1284\0\u12c0\0\u12fc\0\u1338"+
    "\0\u1374\0\u13b0\0\u0870\0\u13ec\0\u1428\0\u1464\0\u14a0\0\u14dc"+
    "\0\u1518\0\u1554\0\u1590\0\u15cc\0\u1608\0\u1644\0\u1680\0\u16bc"+
    "\0\u16f8\0\u1734\0\u1770\0\170\0\u17ac\0\u17e8\0\u1824\0\u1860"+
    "\0\170\0\u189c\0\u18d8\0\u1914\0\u1950\0\u198c\0\u19c8\0\u1a04"+
    "\0\u1a40\0\u1a7c\0\u1ab8\0\u1af4\0\u1b30\0\u1b6c\0\u1ba8\0\u1be4"+
    "\0\u1c20\0\u1c5c\0\u1c98\0\u1cd4\0\u1d10\0\u1d4c\0\170\0\u1d88"+
    "\0\u1dc4\0\u1e00\0\u1e3c\0\u1e78\0\u1eb4\0\u1ef0\0\u1f2c\0\u1f68"+
    "\0\u1fa4\0\u1fe0\0\74\0\u201c\0\u2058\0\u2094\0\u20d0\0\u210c"+
    "\0\u2148\0\u2184\0\u21c0\0\u21fc\0\u2238\0\u2274\0\u22b0\0\u22ec"+
    "\0\u2328\0\u2364\0\u23a0\0\u23dc\0\u2418\0\u2454\0\u2490\0\170"+
    "\0\u24cc\0\u2508\0\u2544\0\170\0\u2580\0\u25bc\0\170\0\u25f8"+
    "\0\u2634\0\u2670\0\170\0\u26ac\0\u26e8\0\u2724\0\u2760\0\u279c"+
    "\0\u27d8\0\u2814\0\u2850\0\u288c\0\170\0\u28c8\0\170\0\u2904"+
    "\0\u2940\0\u297c\0\170\0\170\0\170\0\170\0\u29b8\0\u29f4"+
    "\0\u2a30\0\u2a6c\0\u2aa8\0\u2ae4\0\u2b20\0\u2b5c\0\u2b98\0\u2bd4"+
    "\0\170\0\u2c10\0\170\0\u2c4c\0\u2c88\0\u2cc4\0\170\0\u2d00"+
    "\0\u2d3c\0\u2d78\0\u2db4\0\170\0\u2df0\0\170\0\u2e2c\0\u2e68"+
    "\0\u2ea4\0\170\0\u2ee0\0\170\0\u2f1c\0\u2f58\0\u2f94\0\u2fd0"+
    "\0\u300c\0\u3048\0\170\0\u3084\0\u30c0\0\u30fc\0\u3138\0\170"+
    "\0\u3174\0\170\0\u31b0\0\170\0\u31ec\0\170\0\170\0\u3228"+
    "\0\170\0\u3264\0\170\0\170\0\u32a0\0\u32dc\0\u3318\0\u3354"+
    "\0\170\0\u3390\0\170\0\u33cc\0\u3408\0\170\0\u3444\0\170"+
    "\0\u3480\0\u34bc\0\u34f8\0\u3534\0\u3570\0\u35ac\0\170\0\170"+
    "\0\u35e8\0\u3624\0\u3660\0\u369c\0\u36d8\0\170\0\170\0\170"+
    "\0\170\0\170\0\170\0\u3714\0\u3750\0\170\0\u378c\0\u37c8"+
    "\0\170\0\170\0\170\0\u3804\0\170\0\u3840\0\u387c\0\u38b8"+
    "\0\u38f4\0\u3930\0\u396c\0\u39a8\0\u39e4\0\170\0\170\0\u3a20"+
    "\0\u3a5c\0\u3a98\0\u3ad4\0\u3b10\0\170\0\170\0\u3b4c\0\u3b88"+
    "\0\170\0\170\0\170\0\u3bc4\0\u3c00\0\170\0\170\0\170"+
    "\0\170\0\170\0\u3c3c\0\u3c78\0\170";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[325];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\1\2"+
    "\2\6\1\0\1\10\1\11\1\2\1\12\3\3\1\13"+
    "\1\14\1\3\1\15\1\16\1\17\1\20\1\21\1\3"+
    "\1\22\1\23\2\3\1\24\1\3\1\25\1\3\1\26"+
    "\1\3\1\27\1\30\2\3\1\31\1\32\1\33\1\34"+
    "\3\3\1\35\1\36\1\3\1\37\1\40\1\41\1\3"+
    "\1\42\2\3\1\43\1\3\75\0\2\3\1\44\12\0"+
    "\56\3\2\0\1\4\1\0\1\45\70\0\2\46\1\44"+
    "\12\0\56\46\5\0\1\6\2\0\2\6\62\0\6\47"+
    "\1\50\1\51\1\52\63\47\7\53\1\54\1\52\2\53"+
    "\1\50\60\53\14\0\1\55\1\56\57\0\2\3\1\44"+
    "\12\0\1\3\1\57\3\3\1\60\6\3\1\61\41\3"+
    "\1\0\2\3\1\44\12\0\7\3\1\62\46\3\1\0"+
    "\2\3\1\44\12\0\3\3\1\63\52\3\1\0\2\3"+
    "\1\44\12\0\4\3\1\64\3\3\1\65\45\3\1\0"+
    "\2\3\1\44\12\0\12\3\1\66\43\3\1\0\2\3"+
    "\1\44\12\0\2\3\1\67\53\3\1\0\2\3\1\44"+
    "\12\0\4\3\1\70\3\3\1\71\45\3\1\0\2\3"+
    "\1\44\12\0\2\3\1\72\5\3\1\73\45\3\1\0"+
    "\2\3\1\44\12\0\5\3\1\74\50\3\1\0\2\3"+
    "\1\44\12\0\2\3\1\75\11\3\1\76\41\3\1\0"+
    "\2\3\1\44\12\0\4\3\1\77\1\100\50\3\1\0"+
    "\2\3\1\44\12\0\5\3\1\101\50\3\1\0\2\3"+
    "\1\44\12\0\10\3\1\102\45\3\1\0\2\3\1\44"+
    "\12\0\30\3\1\103\5\3\1\104\17\3\1\0\2\3"+
    "\1\44\12\0\34\3\1\105\21\3\1\0\2\3\1\44"+
    "\12\0\55\3\1\106\1\0\2\3\1\44\12\0\30\3"+
    "\1\107\2\3\1\110\22\3\1\0\2\3\1\44\12\0"+
    "\36\3\1\111\1\112\3\3\1\113\12\3\1\0\2\3"+
    "\1\44\12\0\30\3\1\114\12\3\1\115\12\3\1\0"+
    "\2\3\1\44\12\0\37\3\1\116\3\3\1\117\4\3"+
    "\1\120\5\3\1\0\2\3\1\44\12\0\32\3\1\121"+
    "\12\3\1\122\1\3\1\123\6\3\1\0\2\3\1\44"+
    "\12\0\30\3\1\124\12\3\1\125\12\3\1\0\2\3"+
    "\1\44\12\0\50\3\1\126\5\3\1\0\2\3\1\44"+
    "\12\0\33\3\1\127\7\3\1\130\12\3\1\0\2\3"+
    "\1\44\12\0\43\3\1\131\12\3\1\0\2\3\1\44"+
    "\12\0\36\3\1\132\17\3\1\0\3\44\12\0\56\44"+
    "\2\0\1\133\71\0\10\47\3\0\61\47\10\53\3\0"+
    "\61\53\10\55\1\0\63\55\15\56\1\134\56\56\1\0"+
    "\2\3\1\44\12\0\2\3\1\135\2\3\1\136\2\3"+
    "\1\137\45\3\1\0\2\3\1\44\12\0\1\140\6\3"+
    "\1\141\7\3\1\142\3\3\1\143\2\3\1\144\27\3"+
    "\1\0\2\3\1\44\12\0\5\3\1\145\50\3\1\0"+
    "\2\3\1\44\12\0\3\3\1\146\52\3\1\0\2\3"+
    "\1\44\12\0\6\3\1\147\47\3\1\0\2\3\1\44"+
    "\12\0\20\3\1\150\35\3\1\0\2\3\1\44\12\0"+
    "\11\3\1\151\44\3\1\0\2\3\1\44\12\0\14\3"+
    "\1\152\41\3\1\0\2\3\1\44\12\0\6\3\1\153"+
    "\47\3\1\0\2\3\1\44\12\0\17\3\1\154\36\3"+
    "\1\0\2\3\1\44\12\0\11\3\1\155\44\3\1\0"+
    "\2\3\1\44\12\0\6\3\1\156\47\3\1\0\2\3"+
    "\1\44\12\0\7\3\1\157\46\3\1\0\2\3\1\44"+
    "\12\0\7\3\1\160\46\3\1\0\2\3\1\44\12\0"+
    "\7\3\1\161\2\3\1\162\43\3\1\0\2\3\1\44"+
    "\12\0\4\3\1\163\51\3\1\0\2\3\1\44\12\0"+
    "\13\3\1\164\42\3\1\0\2\3\1\44\12\0\17\3"+
    "\1\165\36\3\1\0\2\3\1\44\12\0\6\3\1\166"+
    "\3\3\1\167\43\3\1\0\2\3\1\44\12\0\22\3"+
    "\1\170\33\3\1\0\2\3\1\44\12\0\31\3\1\171"+
    "\24\3\1\0\2\3\1\44\12\0\50\3\1\172\5\3"+
    "\1\0\2\3\1\44\12\0\45\3\1\173\10\3\1\0"+
    "\2\3\1\44\12\0\33\3\1\174\22\3\1\0\2\3"+
    "\1\44\12\0\31\3\1\175\24\3\1\0\2\3\1\44"+
    "\12\0\47\3\1\176\6\3\1\0\2\3\1\44\12\0"+
    "\37\3\1\177\16\3\1\0\2\3\1\44\12\0\30\3"+
    "\1\200\25\3\1\0\2\3\1\44\12\0\42\3\1\201"+
    "\12\3\1\202\1\0\2\3\1\44\12\0\34\3\1\203"+
    "\21\3\1\0\2\3\1\44\12\0\31\3\1\204\12\3"+
    "\1\205\11\3\1\0\2\3\1\44\12\0\42\3\1\206"+
    "\13\3\1\0\2\3\1\44\12\0\36\3\1\207\17\3"+
    "\1\0\2\3\1\44\12\0\51\3\1\210\4\3\1\0"+
    "\2\3\1\44\12\0\31\3\1\211\24\3\1\0\2\3"+
    "\1\44\12\0\33\3\1\212\22\3\1\0\2\3\1\44"+
    "\12\0\36\3\1\213\17\3\1\0\2\3\1\44\12\0"+
    "\35\3\1\214\20\3\1\0\2\3\1\44\12\0\46\3"+
    "\1\215\7\3\1\0\2\3\1\44\12\0\35\3\1\216"+
    "\20\3\1\0\2\3\1\44\12\0\35\3\1\217\20\3"+
    "\1\0\2\3\1\44\12\0\34\3\1\220\21\3\1\0"+
    "\2\3\1\44\12\0\32\3\1\221\23\3\1\0\2\3"+
    "\1\44\12\0\30\3\1\222\25\3\14\56\1\223\1\134"+
    "\56\56\1\0\2\3\1\44\12\0\3\3\1\224\52\3"+
    "\1\0\2\3\1\44\12\0\12\3\1\225\1\226\42\3"+
    "\1\0\2\3\1\44\12\0\6\3\1\227\1\230\46\3"+
    "\1\0\2\3\1\44\12\0\1\3\1\231\54\3\1\0"+
    "\2\3\1\44\12\0\5\3\1\232\50\3\1\0\2\3"+
    "\1\44\12\0\5\3\1\233\50\3\1\0\2\3\1\44"+
    "\12\0\5\3\1\234\50\3\1\0\2\3\1\44\12\0"+
    "\14\3\1\235\41\3\1\0\2\3\1\44\12\0\22\3"+
    "\1\236\33\3\1\0\2\3\1\44\12\0\6\3\1\237"+
    "\47\3\1\0\2\3\1\44\12\0\5\3\1\240\50\3"+
    "\1\0\2\3\1\44\12\0\14\3\1\241\41\3\1\0"+
    "\2\3\1\44\12\0\2\3\1\242\53\3\1\0\2\3"+
    "\1\44\12\0\3\3\1\243\52\3\1\0\2\3\1\44"+
    "\12\0\2\3\1\244\53\3\1\0\2\3\1\44\12\0"+
    "\5\3\1\245\50\3\1\0\2\3\1\44\12\0\7\3"+
    "\1\246\46\3\1\0\2\3\1\44\12\0\3\3\1\247"+
    "\52\3\1\0\2\3\1\44\12\0\5\3\1\250\50\3"+
    "\1\0\2\3\1\44\12\0\2\3\1\251\53\3\1\0"+
    "\2\3\1\44\12\0\17\3\1\252\36\3\1\0\2\3"+
    "\1\44\12\0\17\3\1\253\36\3\1\0\2\3\1\44"+
    "\12\0\4\3\1\254\51\3\1\0\2\3\1\44\12\0"+
    "\6\3\1\255\47\3\1\0\2\3\1\44\12\0\21\3"+
    "\1\256\34\3\1\0\2\3\1\44\12\0\2\3\1\257"+
    "\53\3\1\0\2\3\1\44\12\0\30\3\1\260\25\3"+
    "\1\0\2\3\1\44\12\0\45\3\1\261\10\3\1\0"+
    "\2\3\1\44\12\0\36\3\1\262\17\3\1\0\2\3"+
    "\1\44\12\0\34\3\1\263\21\3\1\0\2\3\1\44"+
    "\12\0\50\3\1\264\5\3\1\0\2\3\1\44\12\0"+
    "\36\3\1\265\17\3\1\0\2\3\1\44\12\0\40\3"+
    "\1\266\15\3\1\0\2\3\1\44\12\0\36\3\1\267"+
    "\17\3\1\0\2\3\1\44\12\0\30\3\1\270\25\3"+
    "\1\0\2\3\1\44\12\0\33\3\1\271\22\3\1\0"+
    "\2\3\1\44\12\0\46\3\1\272\7\3\1\0\2\3"+
    "\1\44\12\0\46\3\1\273\7\3\1\0\2\3\1\44"+
    "\12\0\43\3\1\274\12\3\1\0\2\3\1\44\12\0"+
    "\43\3\1\275\12\3\1\0\2\3\1\44\12\0\33\3"+
    "\1\276\22\3\1\0\2\3\1\44\12\0\43\3\1\277"+
    "\12\3\1\0\2\3\1\44\12\0\31\3\1\300\24\3"+
    "\1\0\2\3\1\44\12\0\43\3\1\301\12\3\1\0"+
    "\2\3\1\44\12\0\52\3\1\302\3\3\1\0\2\3"+
    "\1\44\12\0\43\3\1\303\12\3\1\0\2\3\1\44"+
    "\12\0\33\3\1\304\22\3\1\0\2\3\1\44\12\0"+
    "\43\3\1\305\12\3\1\0\2\3\1\44\12\0\30\3"+
    "\1\306\25\3\1\0\2\3\1\44\12\0\32\3\1\307"+
    "\23\3\1\0\2\3\1\44\12\0\53\3\1\310\2\3"+
    "\1\0\2\3\1\44\12\0\4\3\1\311\51\3\1\0"+
    "\2\3\1\44\12\0\10\3\1\312\45\3\1\0\2\3"+
    "\1\44\12\0\14\3\1\313\41\3\1\0\2\3\1\44"+
    "\12\0\10\3\1\314\45\3\1\0\2\3\1\44\12\0"+
    "\11\3\1\315\44\3\1\0\2\3\1\44\12\0\10\3"+
    "\1\316\45\3\1\0\2\3\1\44\12\0\1\317\55\3"+
    "\1\0\2\3\1\44\12\0\17\3\1\320\36\3\1\0"+
    "\2\3\1\44\12\0\17\3\1\321\36\3\1\0\2\3"+
    "\1\44\12\0\4\3\1\322\51\3\1\0\2\3\1\44"+
    "\12\0\4\3\1\323\51\3\1\0\2\3\1\44\12\0"+
    "\4\3\1\324\51\3\1\0\2\3\1\44\12\0\13\3"+
    "\1\325\42\3\1\0\2\3\1\44\12\0\10\3\1\326"+
    "\45\3\1\0\2\3\1\44\12\0\12\3\1\327\43\3"+
    "\1\0\2\3\1\44\12\0\10\3\1\330\45\3\1\0"+
    "\2\3\1\44\12\0\12\3\1\331\43\3\1\0\2\3"+
    "\1\44\12\0\10\3\1\332\45\3\1\0\2\3\1\44"+
    "\12\0\10\3\1\333\45\3\1\0\2\3\1\44\12\0"+
    "\2\3\1\334\2\3\1\335\50\3\1\0\2\3\1\44"+
    "\12\0\7\3\1\336\46\3\1\0\2\3\1\44\12\0"+
    "\3\3\1\337\52\3\1\0\2\3\1\44\12\0\5\3"+
    "\1\340\50\3\1\0\2\3\1\44\12\0\10\3\1\341"+
    "\45\3\1\0\2\3\1\44\12\0\5\3\1\342\50\3"+
    "\1\0\2\3\1\44\12\0\32\3\1\343\23\3\1\0"+
    "\2\3\1\44\12\0\33\3\1\344\22\3\1\0\2\3"+
    "\1\44\12\0\30\3\1\345\25\3\1\0\2\3\1\44"+
    "\12\0\32\3\1\346\23\3\1\0\2\3\1\44\12\0"+
    "\43\3\1\347\12\3\1\0\2\3\1\44\12\0\41\3"+
    "\1\350\14\3\1\0\2\3\1\44\12\0\46\3\1\351"+
    "\7\3\1\0\2\3\1\44\12\0\53\3\1\352\2\3"+
    "\1\0\2\3\1\44\12\0\53\3\1\353\2\3\1\0"+
    "\2\3\1\44\12\0\43\3\1\354\12\3\1\0\2\3"+
    "\1\44\12\0\43\3\1\355\12\3\1\0\2\3\1\44"+
    "\12\0\41\3\1\356\14\3\1\0\2\3\1\44\12\0"+
    "\36\3\1\357\17\3\1\0\2\3\1\44\12\0\33\3"+
    "\1\360\22\3\1\0\2\3\1\44\12\0\40\3\1\361"+
    "\15\3\1\0\2\3\1\44\12\0\33\3\1\362\22\3"+
    "\1\0\2\3\1\44\12\0\43\3\1\363\12\3\1\0"+
    "\2\3\1\44\12\0\33\3\1\364\22\3\1\0\2\3"+
    "\1\44\12\0\5\3\1\365\50\3\1\0\2\3\1\44"+
    "\12\0\12\3\1\366\43\3\1\0\2\3\1\44\12\0"+
    "\7\3\1\367\46\3\1\0\2\3\1\44\12\0\13\3"+
    "\1\370\42\3\1\0\2\3\1\44\12\0\4\3\1\371"+
    "\51\3\1\0\2\3\1\44\12\0\3\3\1\372\52\3"+
    "\1\0\2\3\1\44\12\0\5\3\1\373\50\3\1\0"+
    "\2\3\1\44\12\0\4\3\1\374\51\3\1\0\2\3"+
    "\1\44\12\0\6\3\1\375\47\3\1\0\2\3\1\44"+
    "\12\0\12\3\1\376\43\3\1\0\2\3\1\44\12\0"+
    "\5\3\1\377\50\3\1\0\2\3\1\44\12\0\17\3"+
    "\1\u0100\36\3\1\0\2\3\1\44\12\0\17\3\1\u0101"+
    "\36\3\1\0\2\3\1\44\12\0\20\3\1\u0102\35\3"+
    "\1\0\2\3\1\44\12\0\7\3\1\u0103\46\3\1\0"+
    "\2\3\1\44\12\0\5\3\1\u0104\50\3\1\0\2\3"+
    "\1\44\12\0\24\3\1\u0105\31\3\1\0\2\3\1\44"+
    "\12\0\5\3\1\u0106\50\3\1\0\2\3\1\44\12\0"+
    "\12\3\1\u0107\43\3\1\0\2\3\1\44\12\0\2\3"+
    "\1\u0108\53\3\1\0\2\3\1\44\12\0\33\3\1\u0109"+
    "\22\3\1\0\2\3\1\44\12\0\32\3\1\u010a\23\3"+
    "\1\0\2\3\1\44\12\0\32\3\1\u010b\23\3\1\0"+
    "\2\3\1\44\12\0\41\3\1\u010c\14\3\1\0\2\3"+
    "\1\44\12\0\35\3\1\u010d\4\3\1\u010e\13\3\1\0"+
    "\2\3\1\44\12\0\33\3\1\u010f\22\3\1\0\2\3"+
    "\1\44\12\0\43\3\1\u0110\12\3\1\0\2\3\1\44"+
    "\12\0\53\3\1\u0111\2\3\1\0\2\3\1\44\12\0"+
    "\41\3\1\u0112\14\3\1\0\2\3\1\44\12\0\36\3"+
    "\1\u0113\3\3\1\u0114\13\3\1\0\2\3\1\44\12\0"+
    "\35\3\1\u0115\20\3\1\0\2\3\1\44\12\0\33\3"+
    "\1\u0116\22\3\1\0\2\3\1\44\12\0\34\3\1\u0117"+
    "\21\3\1\0\2\3\1\44\12\0\6\3\1\u0118\47\3"+
    "\1\0\2\3\1\44\12\0\5\3\1\u0119\50\3\1\0"+
    "\2\3\1\44\12\0\2\3\1\u011a\53\3\1\0\2\3"+
    "\1\44\12\0\2\3\1\u011b\53\3\1\0\2\3\1\44"+
    "\12\0\5\3\1\u011c\50\3\1\0\2\3\1\44\12\0"+
    "\17\3\1\u011d\36\3\1\0\2\3\1\44\12\0\4\3"+
    "\1\u011e\51\3\1\0\2\3\1\44\12\0\5\3\1\u011f"+
    "\50\3\1\0\2\3\1\44\12\0\1\u0120\55\3\1\0"+
    "\2\3\1\44\12\0\2\3\1\u0121\53\3\1\0\2\3"+
    "\1\44\12\0\2\3\1\u0122\53\3\1\0\2\3\1\44"+
    "\12\0\34\3\1\u0123\21\3\1\0\2\3\1\44\12\0"+
    "\32\3\1\u0124\23\3\1\0\2\3\1\44\12\0\43\3"+
    "\1\u0125\12\3\1\0\2\3\1\44\12\0\42\3\1\u0126"+
    "\13\3\1\0\2\3\1\44\12\0\36\3\1\u0127\17\3"+
    "\1\0\2\3\1\44\12\0\43\3\1\u0128\12\3\1\0"+
    "\2\3\1\44\12\0\42\3\1\u0129\13\3\1\0\2\3"+
    "\1\44\12\0\42\3\1\u012a\13\3\1\0\2\3\1\44"+
    "\12\0\43\3\1\u012b\12\3\1\0\2\3\1\44\12\0"+
    "\43\3\1\u012c\12\3\1\0\2\3\1\44\12\0\50\3"+
    "\1\u012d\5\3\1\0\2\3\1\44\12\0\6\3\1\u012e"+
    "\47\3\1\0\2\3\1\44\12\0\2\3\1\u012f\53\3"+
    "\1\0\2\3\1\44\12\0\24\3\1\u0130\31\3\1\0"+
    "\2\3\1\44\12\0\5\3\1\u0131\50\3\1\0\2\3"+
    "\1\44\12\0\43\3\1\u0132\12\3\1\0\2\3\1\44"+
    "\12\0\43\3\1\u0133\12\3\1\0\2\3\1\44\12\0"+
    "\37\3\1\u0134\16\3\1\0\2\3\1\44\12\0\36\3"+
    "\1\u0135\17\3\1\0\2\3\1\44\12\0\33\3\1\u0136"+
    "\22\3\1\0\2\3\1\44\12\0\43\3\1\u0137\12\3"+
    "\1\0\2\3\1\44\12\0\44\3\1\u0138\11\3\1\0"+
    "\2\3\1\44\12\0\36\3\1\u0139\17\3\1\0\2\3"+
    "\1\44\12\0\33\3\1\u013a\22\3\1\0\2\3\1\44"+
    "\12\0\2\3\1\u013b\53\3\1\0\2\3\1\44\12\0"+
    "\7\3\1\u013c\46\3\1\0\2\3\1\44\12\0\41\3"+
    "\1\u013d\14\3\1\0\2\3\1\44\12\0\36\3\1\u013e"+
    "\17\3\1\0\2\3\1\44\12\0\40\3\1\u013f\15\3"+
    "\1\0\2\3\1\44\12\0\36\3\1\u0140\17\3\1\0"+
    "\2\3\1\44\12\0\43\3\1\u0141\12\3\1\0\2\3"+
    "\1\44\12\0\2\3\1\u0142\53\3\1\0\2\3\1\44"+
    "\12\0\42\3\1\u0143\13\3\1\0\2\3\1\44\12\0"+
    "\43\3\1\u0144\12\3\1\0\2\3\1\44\12\0\36\3"+
    "\1\u0145\17\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15540];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\42\1\3\0\1\11\1\0\1\11\2\0"+
    "\146\1\1\11\262\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[325];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private final List<LexicalError> errors = new ArrayList<>();

    public List<LexicalError> getErrors() {
        return errors;
    }

    private Token token(TokenType type) {
        return new Token(yytext(), type, yyline + 1, yycolumn + 1);
    }

    private void lexicalError(String message) {
        errors.add(new LexicalError(
            yytext(),
            message,
            yyline + 1,
            yycolumn + 1
        ));
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 240) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return token(TokenType.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexicalError("Símbolo no reconocido"); return token(TokenType.ERROR);
            } 
            // fall through
          case 74: break;
          case 2: 
            { return token(TokenType.IDENTIFIER);
            } 
            // fall through
          case 75: break;
          case 3: 
            { return token(TokenType.INTEGER_LITERAL);
            } 
            // fall through
          case 76: break;
          case 4: 
            { /* ignorar */
            } 
            // fall through
          case 77: break;
          case 5: 
            { lexicalError("Identificador inválido: no se permiten tildes ni la letra ñ"); return token(TokenType.ERROR);
            } 
            // fall through
          case 78: break;
          case 6: 
            { return token(TokenType.STRING_LITERAL);
            } 
            // fall through
          case 79: break;
          case 7: 
            { lexicalError("Cadena de texto no cerrada"); return token(TokenType.ERROR);
            } 
            // fall through
          case 80: break;
          case 8: 
            { lexicalError("Comentario de bloque no cerrado"); return token(TokenType.ERROR);
            } 
            // fall through
          case 81: break;
          case 9: 
            { return token(TokenType.DECIMAL_LITERAL);
            } 
            // fall through
          case 82: break;
          case 10: 
            { return token(TokenType.FALSE);
            } 
            // fall through
          case 83: break;
          case 11: 
            { return token(TokenType.THIS);
            } 
            // fall through
          case 84: break;
          case 12: 
            { return token(TokenType.ASSIGN);
            } 
            // fall through
          case 85: break;
          case 13: 
            { return token(TokenType.CASE);
            } 
            // fall through
          case 86: break;
          case 14: 
            { return token(TokenType.DO);
            } 
            // fall through
          case 87: break;
          case 15: 
            { return token(TokenType.CONST);
            } 
            // fall through
          case 88: break;
          case 16: 
            { return token(TokenType.COLON);
            } 
            // fall through
          case 89: break;
          case 17: 
            { return token(TokenType.PLUS);
            } 
            // fall through
          case 90: break;
          case 18: 
            { return token(TokenType.MINUS);
            } 
            // fall through
          case 91: break;
          case 19: 
            { return token(TokenType.QUESTION);
            } 
            // fall through
          case 92: break;
          case 20: 
            { return token(TokenType.LEFT_BRACE);
            } 
            // fall through
          case 93: break;
          case 21: 
            { return token(TokenType.RIGHT_BRACKET);
            } 
            // fall through
          case 94: break;
          case 22: 
            { return token(TokenType.LESS_THAN);
            } 
            // fall through
          case 95: break;
          case 23: 
            { return token(TokenType.GREATER_THAN);
            } 
            // fall through
          case 96: break;
          case 24: 
            { return token(TokenType.LESS_EQUAL);
            } 
            // fall through
          case 97: break;
          case 25: 
            { return token(TokenType.INT);
            } 
            // fall through
          case 98: break;
          case 26: 
            { return token(TokenType.BREAK);
            } 
            // fall through
          case 99: break;
          case 27: 
            { return token(TokenType.IF);
            } 
            // fall through
          case 100: break;
          case 28: 
            { return token(TokenType.FLOAT);
            } 
            // fall through
          case 101: break;
          case 29: 
            { return token(TokenType.RETURN);
            } 
            // fall through
          case 102: break;
          case 30: 
            { return token(TokenType.CLASS);
            } 
            // fall through
          case 103: break;
          case 31: 
            { return token(TokenType.NOT);
            } 
            // fall through
          case 104: break;
          case 32: 
            { return token(TokenType.MOD);
            } 
            // fall through
          case 105: break;
          case 33: 
            { return token(TokenType.LEFT_BRACKET);
            } 
            // fall through
          case 106: break;
          case 34: 
            { return token(TokenType.DIVIDE);
            } 
            // fall through
          case 107: break;
          case 35: 
            { return token(TokenType.DOT);
            } 
            // fall through
          case 108: break;
          case 36: 
            { return token(TokenType.GREATER_EQUAL);
            } 
            // fall through
          case 109: break;
          case 37: 
            { return token(TokenType.SEMICOLON);
            } 
            // fall through
          case 110: break;
          case 38: 
            { return token(TokenType.CONTINUE);
            } 
            // fall through
          case 111: break;
          case 39: 
            { return token(TokenType.ELSE);
            } 
            // fall through
          case 112: break;
          case 40: 
            { return token(TokenType.STRING);
            } 
            // fall through
          case 113: break;
          case 41: 
            { return token(TokenType.BOOL);
            } 
            // fall through
          case 114: break;
          case 42: 
            { return token(TokenType.TRY);
            } 
            // fall through
          case 115: break;
          case 43: 
            { return token(TokenType.NULL);
            } 
            // fall through
          case 116: break;
          case 44: 
            { return token(TokenType.VOID);
            } 
            // fall through
          case 117: break;
          case 45: 
            { return token(TokenType.FOR);
            } 
            // fall through
          case 118: break;
          case 46: 
            { return token(TokenType.PUBLIC);
            } 
            // fall through
          case 119: break;
          case 47: 
            { return token(TokenType.RIGHT_BRACE);
            } 
            // fall through
          case 120: break;
          case 48: 
            { return token(TokenType.AND);
            } 
            // fall through
          case 121: break;
          case 49: 
            { return token(TokenType.LEFT_PAREN);
            } 
            // fall through
          case 122: break;
          case 50: 
            { return token(TokenType.OR);
            } 
            // fall through
          case 123: break;
          case 51: 
            { return token(TokenType.PRINT);
            } 
            // fall through
          case 124: break;
          case 52: 
            { return token(TokenType.SWITCH);
            } 
            // fall through
          case 125: break;
          case 53: 
            { return token(TokenType.CHAR);
            } 
            // fall through
          case 126: break;
          case 54: 
            { return token(TokenType.PRIVATE);
            } 
            // fall through
          case 127: break;
          case 55: 
            { return token(TokenType.WHILE);
            } 
            // fall through
          case 128: break;
          case 56: 
            { return token(TokenType.DOUBLE);
            } 
            // fall through
          case 129: break;
          case 57: 
            { return token(TokenType.TRUE);
            } 
            // fall through
          case 130: break;
          case 58: 
            { return token(TokenType.EQUALS);
            } 
            // fall through
          case 131: break;
          case 59: 
            { return token(TokenType.COMMA);
            } 
            // fall through
          case 132: break;
          case 60: 
            { return token(TokenType.NEW);
            } 
            // fall through
          case 133: break;
          case 61: 
            { return token(TokenType.CATCH);
            } 
            // fall through
          case 134: break;
          case 62: 
            { return token(TokenType.MULTIPLY);
            } 
            // fall through
          case 135: break;
          case 63: 
            { return token(TokenType.PLUS_ASSIGN);
            } 
            // fall through
          case 136: break;
          case 64: 
            { return token(TokenType.RIGHT_PAREN);
            } 
            // fall through
          case 137: break;
          case 65: 
            { return token(TokenType.MINUS_ASSIGN);
            } 
            // fall through
          case 138: break;
          case 66: 
            { return token(TokenType.NOT_EQUALS);
            } 
            // fall through
          case 139: break;
          case 67: 
            { return token(TokenType.THROW);
            } 
            // fall through
          case 140: break;
          case 68: 
            { return token(TokenType.MOD_ASSIGN);
            } 
            // fall through
          case 141: break;
          case 69: 
            { return token(TokenType.INCREMENT);
            } 
            // fall through
          case 142: break;
          case 70: 
            { return token(TokenType.DIVIDE_ASSIGN);
            } 
            // fall through
          case 143: break;
          case 71: 
            { return token(TokenType.DECREMENT);
            } 
            // fall through
          case 144: break;
          case 72: 
            { return token(TokenType.DEFAULT);
            } 
            // fall through
          case 145: break;
          case 73: 
            { return token(TokenType.MULTIPLY_ASSIGN);
            } 
            // fall through
          case 146: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
