/* The following code was generated by JFlex 1.7.0 */

package org.example.lexer;

import java.util.ArrayList;
import java.util.List;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/main/java/org/example/lexer/Lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\10\1\12\1\12\1\11\22\0\1\5\1\46\1\6"+
    "\3\0\1\51\1\13\1\61\1\62\1\15\1\53\1\56\1\54\1\4"+
    "\1\14\12\2\1\60\1\55\1\47\1\45\1\50\1\57\1\0\32\1"+
    "\1\65\1\7\1\66\1\0\1\1\1\0\1\23\1\41\1\16\1\37"+
    "\1\22\1\43\1\36\1\17\1\26\1\40\1\1\1\35\1\27\1\30"+
    "\1\20\1\31\1\44\1\24\1\25\1\21\1\32\1\34\1\33\2\1"+
    "\1\42\1\63\1\52\1\64\7\0\1\12\73\0\1\3\7\0\1\3"+
    "\3\0\1\3\3\0\1\3\1\0\1\3\6\0\1\3\6\0\1\3"+
    "\7\0\1\3\3\0\1\3\3\0\1\3\1\0\1\3\6\0\1\3"+
    "\u1f2d\0\1\12\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\2\1"+
    "\1\6\1\7\13\2\1\10\1\11\1\12\1\13\2\1"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\3\0\1\31\1\0"+
    "\1\32\2\0\1\5\1\33\22\2\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\33\15\2\1\43\4\2"+
    "\1\44\7\2\1\5\22\2\1\45\3\2\1\46\2\2"+
    "\1\47\10\2\1\50\1\2\1\51\2\2\1\52\3\2"+
    "\1\53\1\2\1\54\3\2\1\55\1\2\1\56\1\57"+
    "\1\2\1\60\1\2\1\61\1\62\4\2\1\63\2\2"+
    "\1\64\1\2\1\65\1\66\1\67\1\70\1\71\1\2"+
    "\1\72\2\2\1\73\1\74\1\75\2\2\1\76\1\2"+
    "\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[188];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\67\0\u0113\0\u014a"+
    "\0\u0181\0\u01b8\0\67\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb"+
    "\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\67\0\67\0\67"+
    "\0\u0596\0\u05cd\0\334\0\u014a\0\67\0\u0604\0\67\0\u0181"+
    "\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc"+
    "\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974"+
    "\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\u05cd\0\u0abe\0\u0af5\0\u0b2c\0\u0b63"+
    "\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b"+
    "\0\u0d52\0\u0d89\0\156\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\156"+
    "\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\67"+
    "\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e"+
    "\0\u11d5\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356"+
    "\0\u138d\0\u13c4\0\156\0\u13fb\0\u1432\0\u1469\0\156\0\u14a0"+
    "\0\u14d7\0\156\0\u150e\0\u1545\0\u157c\0\u15b3\0\u15ea\0\u1621"+
    "\0\u1658\0\u168f\0\156\0\u16c6\0\156\0\u16fd\0\u1734\0\156"+
    "\0\u176b\0\u17a2\0\u17d9\0\156\0\u1810\0\156\0\u1847\0\u187e"+
    "\0\u18b5\0\156\0\u18ec\0\156\0\156\0\u1923\0\156\0\u195a"+
    "\0\156\0\156\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\156\0\u1a6d"+
    "\0\u1aa4\0\156\0\u1adb\0\156\0\156\0\156\0\156\0\156"+
    "\0\u1b12\0\156\0\u1b49\0\u1b80\0\156\0\156\0\156\0\u1bb7"+
    "\0\u1bee\0\156\0\u1c25\0\156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[188];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\2\7\1\0\1\11\1\12\1\13\1\14\4\3\1\15"+
    "\1\3\1\16\1\3\1\17\1\20\1\21\1\3\1\22"+
    "\1\23\2\3\1\24\1\3\1\25\1\3\1\26\1\3"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\70\0\2\3\1\51\12\0\27\3\24\0"+
    "\1\4\1\0\1\52\63\0\2\53\1\51\12\0\27\53"+
    "\27\0\1\7\2\0\2\7\55\0\6\54\1\55\1\56"+
    "\1\57\56\54\7\60\1\61\1\57\2\60\1\55\53\60"+
    "\14\0\1\62\1\63\52\0\2\3\1\51\12\0\1\3"+
    "\1\64\3\3\1\65\6\3\1\66\12\3\23\0\2\3"+
    "\1\51\12\0\3\3\1\67\23\3\23\0\2\3\1\51"+
    "\12\0\4\3\1\70\3\3\1\71\16\3\23\0\2\3"+
    "\1\51\12\0\2\3\1\72\24\3\23\0\2\3\1\51"+
    "\12\0\4\3\1\73\3\3\1\74\16\3\23\0\2\3"+
    "\1\51\12\0\2\3\1\75\5\3\1\76\16\3\23\0"+
    "\2\3\1\51\12\0\5\3\1\77\21\3\23\0\2\3"+
    "\1\51\12\0\2\3\1\100\11\3\1\101\12\3\23\0"+
    "\2\3\1\51\12\0\4\3\1\102\1\103\21\3\23\0"+
    "\2\3\1\51\12\0\5\3\1\104\21\3\23\0\2\3"+
    "\1\51\12\0\10\3\1\105\16\3\67\0\1\106\66\0"+
    "\1\107\66\0\1\110\66\0\1\111\72\0\1\112\67\0"+
    "\1\113\15\0\3\51\12\0\27\51\24\0\1\114\64\0"+
    "\10\54\3\0\54\54\10\60\3\0\54\60\10\62\1\0"+
    "\56\62\15\63\1\115\51\63\1\0\2\3\1\51\12\0"+
    "\2\3\1\116\2\3\1\117\2\3\1\120\16\3\23\0"+
    "\2\3\1\51\12\0\1\121\6\3\1\122\7\3\1\123"+
    "\3\3\1\124\2\3\1\125\23\0\2\3\1\51\12\0"+
    "\5\3\1\126\21\3\23\0\2\3\1\51\12\0\6\3"+
    "\1\127\20\3\23\0\2\3\1\51\12\0\20\3\1\130"+
    "\6\3\23\0\2\3\1\51\12\0\11\3\1\131\15\3"+
    "\23\0\2\3\1\51\12\0\6\3\1\132\20\3\23\0"+
    "\2\3\1\51\12\0\17\3\1\133\7\3\23\0\2\3"+
    "\1\51\12\0\11\3\1\134\15\3\23\0\2\3\1\51"+
    "\12\0\6\3\1\135\20\3\23\0\2\3\1\51\12\0"+
    "\7\3\1\136\17\3\23\0\2\3\1\51\12\0\7\3"+
    "\1\137\17\3\23\0\2\3\1\51\12\0\7\3\1\140"+
    "\2\3\1\141\14\3\23\0\2\3\1\51\12\0\4\3"+
    "\1\142\22\3\23\0\2\3\1\51\12\0\13\3\1\143"+
    "\13\3\23\0\2\3\1\51\12\0\17\3\1\144\7\3"+
    "\23\0\2\3\1\51\12\0\6\3\1\145\3\3\1\146"+
    "\14\3\23\0\2\3\1\51\12\0\22\3\1\147\4\3"+
    "\22\0\14\63\1\150\1\115\51\63\1\0\2\3\1\51"+
    "\12\0\3\3\1\151\23\3\23\0\2\3\1\51\12\0"+
    "\12\3\1\152\1\153\13\3\23\0\2\3\1\51\12\0"+
    "\6\3\1\154\1\155\17\3\23\0\2\3\1\51\12\0"+
    "\1\3\1\156\25\3\23\0\2\3\1\51\12\0\5\3"+
    "\1\157\21\3\23\0\2\3\1\51\12\0\5\3\1\160"+
    "\21\3\23\0\2\3\1\51\12\0\5\3\1\161\21\3"+
    "\23\0\2\3\1\51\12\0\14\3\1\162\12\3\23\0"+
    "\2\3\1\51\12\0\22\3\1\163\4\3\23\0\2\3"+
    "\1\51\12\0\5\3\1\164\21\3\23\0\2\3\1\51"+
    "\12\0\14\3\1\165\12\3\23\0\2\3\1\51\12\0"+
    "\2\3\1\166\24\3\23\0\2\3\1\51\12\0\2\3"+
    "\1\167\24\3\23\0\2\3\1\51\12\0\5\3\1\170"+
    "\21\3\23\0\2\3\1\51\12\0\7\3\1\171\17\3"+
    "\23\0\2\3\1\51\12\0\3\3\1\172\23\3\23\0"+
    "\2\3\1\51\12\0\5\3\1\173\21\3\23\0\2\3"+
    "\1\51\12\0\2\3\1\174\24\3\23\0\2\3\1\51"+
    "\12\0\17\3\1\175\7\3\23\0\2\3\1\51\12\0"+
    "\17\3\1\176\7\3\23\0\2\3\1\51\12\0\4\3"+
    "\1\177\22\3\23\0\2\3\1\51\12\0\6\3\1\200"+
    "\20\3\23\0\2\3\1\51\12\0\21\3\1\201\5\3"+
    "\23\0\2\3\1\51\12\0\2\3\1\202\24\3\23\0"+
    "\2\3\1\51\12\0\4\3\1\203\22\3\23\0\2\3"+
    "\1\51\12\0\10\3\1\204\16\3\23\0\2\3\1\51"+
    "\12\0\14\3\1\205\12\3\23\0\2\3\1\51\12\0"+
    "\10\3\1\206\16\3\23\0\2\3\1\51\12\0\11\3"+
    "\1\207\15\3\23\0\2\3\1\51\12\0\10\3\1\210"+
    "\16\3\23\0\2\3\1\51\12\0\1\211\26\3\23\0"+
    "\2\3\1\51\12\0\17\3\1\212\7\3\23\0\2\3"+
    "\1\51\12\0\17\3\1\213\7\3\23\0\2\3\1\51"+
    "\12\0\4\3\1\214\22\3\23\0\2\3\1\51\12\0"+
    "\4\3\1\215\22\3\23\0\2\3\1\51\12\0\13\3"+
    "\1\216\13\3\23\0\2\3\1\51\12\0\10\3\1\217"+
    "\16\3\23\0\2\3\1\51\12\0\12\3\1\220\14\3"+
    "\23\0\2\3\1\51\12\0\12\3\1\221\14\3\23\0"+
    "\2\3\1\51\12\0\10\3\1\222\16\3\23\0\2\3"+
    "\1\51\12\0\10\3\1\223\16\3\23\0\2\3\1\51"+
    "\12\0\2\3\1\224\2\3\1\225\21\3\23\0\2\3"+
    "\1\51\12\0\7\3\1\226\17\3\23\0\2\3\1\51"+
    "\12\0\3\3\1\227\23\3\23\0\2\3\1\51\12\0"+
    "\5\3\1\230\21\3\23\0\2\3\1\51\12\0\10\3"+
    "\1\231\16\3\23\0\2\3\1\51\12\0\5\3\1\232"+
    "\21\3\23\0\2\3\1\51\12\0\5\3\1\233\21\3"+
    "\23\0\2\3\1\51\12\0\12\3\1\234\14\3\23\0"+
    "\2\3\1\51\12\0\7\3\1\235\17\3\23\0\2\3"+
    "\1\51\12\0\13\3\1\236\13\3\23\0\2\3\1\51"+
    "\12\0\4\3\1\237\22\3\23\0\2\3\1\51\12\0"+
    "\3\3\1\240\23\3\23\0\2\3\1\51\12\0\5\3"+
    "\1\241\21\3\23\0\2\3\1\51\12\0\4\3\1\242"+
    "\22\3\23\0\2\3\1\51\12\0\6\3\1\243\20\3"+
    "\23\0\2\3\1\51\12\0\5\3\1\244\21\3\23\0"+
    "\2\3\1\51\12\0\17\3\1\245\7\3\23\0\2\3"+
    "\1\51\12\0\20\3\1\246\6\3\23\0\2\3\1\51"+
    "\12\0\7\3\1\247\17\3\23\0\2\3\1\51\12\0"+
    "\5\3\1\250\21\3\23\0\2\3\1\51\12\0\24\3"+
    "\1\251\2\3\23\0\2\3\1\51\12\0\5\3\1\252"+
    "\21\3\23\0\2\3\1\51\12\0\12\3\1\253\14\3"+
    "\23\0\2\3\1\51\12\0\2\3\1\254\24\3\23\0"+
    "\2\3\1\51\12\0\6\3\1\255\20\3\23\0\2\3"+
    "\1\51\12\0\5\3\1\256\21\3\23\0\2\3\1\51"+
    "\12\0\2\3\1\257\24\3\23\0\2\3\1\51\12\0"+
    "\2\3\1\260\24\3\23\0\2\3\1\51\12\0\17\3"+
    "\1\261\7\3\23\0\2\3\1\51\12\0\4\3\1\262"+
    "\22\3\23\0\2\3\1\51\12\0\5\3\1\263\21\3"+
    "\23\0\2\3\1\51\12\0\1\264\26\3\23\0\2\3"+
    "\1\51\12\0\2\3\1\265\24\3\23\0\2\3\1\51"+
    "\12\0\2\3\1\266\24\3\23\0\2\3\1\51\12\0"+
    "\2\3\1\267\24\3\23\0\2\3\1\51\12\0\24\3"+
    "\1\270\2\3\23\0\2\3\1\51\12\0\5\3\1\271"+
    "\21\3\23\0\2\3\1\51\12\0\2\3\1\272\24\3"+
    "\23\0\2\3\1\51\12\0\7\3\1\273\17\3\23\0"+
    "\2\3\1\51\12\0\2\3\1\274\24\3\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7260];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\4\1\1\11\21\1\14\11"+
    "\1\1\3\0\1\11\1\0\1\11\2\0\24\1\6\11"+
    "\34\1\1\11\124\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[188];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private final List<LexicalError> errors = new ArrayList<>();

    public List<LexicalError> getErrors() {
        return errors;
    }

    private Token token(TokenType type) {
        return new Token(yytext(), type, yyline + 1, yycolumn + 1);
    }

    private void lexicalError(String message) {
        errors.add(new LexicalError(
            yytext(),
            message,
            yyline + 1,
            yycolumn + 1
        ));
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 220) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return token(TokenType.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexicalError("Símbolo no reconocido"); return token(TokenType.ERROR);
            } 
            // fall through
          case 64: break;
          case 2: 
            { return token(TokenType.IDENTIFIER);
            } 
            // fall through
          case 65: break;
          case 3: 
            { return token(TokenType.INTEGER_LITERAL);
            } 
            // fall through
          case 66: break;
          case 4: 
            { return token(TokenType.DOT);
            } 
            // fall through
          case 67: break;
          case 5: 
            { /* ignorar */
            } 
            // fall through
          case 68: break;
          case 6: 
            { return token(TokenType.DIVIDE);
            } 
            // fall through
          case 69: break;
          case 7: 
            { return token(TokenType.MULTIPLY);
            } 
            // fall through
          case 70: break;
          case 8: 
            { return token(TokenType.ASSIGN);
            } 
            // fall through
          case 71: break;
          case 9: 
            { return token(TokenType.NOT);
            } 
            // fall through
          case 72: break;
          case 10: 
            { return token(TokenType.LESS_THAN);
            } 
            // fall through
          case 73: break;
          case 11: 
            { return token(TokenType.GREATER_THAN);
            } 
            // fall through
          case 74: break;
          case 12: 
            { return token(TokenType.PLUS);
            } 
            // fall through
          case 75: break;
          case 13: 
            { return token(TokenType.MINUS);
            } 
            // fall through
          case 76: break;
          case 14: 
            { return token(TokenType.SEMICOLON);
            } 
            // fall through
          case 77: break;
          case 15: 
            { return token(TokenType.COMMA);
            } 
            // fall through
          case 78: break;
          case 16: 
            { return token(TokenType.QUESTION);
            } 
            // fall through
          case 79: break;
          case 17: 
            { return token(TokenType.COLON);
            } 
            // fall through
          case 80: break;
          case 18: 
            { return token(TokenType.LEFT_PAREN);
            } 
            // fall through
          case 81: break;
          case 19: 
            { return token(TokenType.RIGHT_PAREN);
            } 
            // fall through
          case 82: break;
          case 20: 
            { return token(TokenType.LEFT_BRACE);
            } 
            // fall through
          case 83: break;
          case 21: 
            { return token(TokenType.RIGHT_BRACE);
            } 
            // fall through
          case 84: break;
          case 22: 
            { return token(TokenType.LEFT_BRACKET);
            } 
            // fall through
          case 85: break;
          case 23: 
            { return token(TokenType.RIGHT_BRACKET);
            } 
            // fall through
          case 86: break;
          case 24: 
            { lexicalError("Identificador inválido: no se permiten tildes ni la letra ñ"); return token(TokenType.ERROR);
            } 
            // fall through
          case 87: break;
          case 25: 
            { return token(TokenType.STRING_LITERAL);
            } 
            // fall through
          case 88: break;
          case 26: 
            { lexicalError("Cadena de texto no cerrada"); return token(TokenType.ERROR);
            } 
            // fall through
          case 89: break;
          case 27: 
            { lexicalError("Comentario de bloque no cerrado"); return token(TokenType.ERROR);
            } 
            // fall through
          case 90: break;
          case 28: 
            { return token(TokenType.EQUALS);
            } 
            // fall through
          case 91: break;
          case 29: 
            { return token(TokenType.NOT_EQUALS);
            } 
            // fall through
          case 92: break;
          case 30: 
            { return token(TokenType.LESS_EQUAL);
            } 
            // fall through
          case 93: break;
          case 31: 
            { return token(TokenType.GREATER_EQUAL);
            } 
            // fall through
          case 94: break;
          case 32: 
            { return token(TokenType.AND);
            } 
            // fall through
          case 95: break;
          case 33: 
            { return token(TokenType.OR);
            } 
            // fall through
          case 96: break;
          case 34: 
            { return token(TokenType.DECIMAL_LITERAL);
            } 
            // fall through
          case 97: break;
          case 35: 
            { return token(TokenType.FALSE);
            } 
            // fall through
          case 98: break;
          case 36: 
            { return token(TokenType.THIS);
            } 
            // fall through
          case 99: break;
          case 37: 
            { return token(TokenType.CASE);
            } 
            // fall through
          case 100: break;
          case 38: 
            { return token(TokenType.DO);
            } 
            // fall through
          case 101: break;
          case 39: 
            { return token(TokenType.CONST);
            } 
            // fall through
          case 102: break;
          case 40: 
            { return token(TokenType.INT);
            } 
            // fall through
          case 103: break;
          case 41: 
            { return token(TokenType.BREAK);
            } 
            // fall through
          case 104: break;
          case 42: 
            { return token(TokenType.IF);
            } 
            // fall through
          case 105: break;
          case 43: 
            { return token(TokenType.FLOAT);
            } 
            // fall through
          case 106: break;
          case 44: 
            { return token(TokenType.RETURN);
            } 
            // fall through
          case 107: break;
          case 45: 
            { return token(TokenType.CLASS);
            } 
            // fall through
          case 108: break;
          case 46: 
            { return token(TokenType.CONTINUE);
            } 
            // fall through
          case 109: break;
          case 47: 
            { return token(TokenType.ELSE);
            } 
            // fall through
          case 110: break;
          case 48: 
            { return token(TokenType.STRING);
            } 
            // fall through
          case 111: break;
          case 49: 
            { return token(TokenType.BOOL);
            } 
            // fall through
          case 112: break;
          case 50: 
            { return token(TokenType.TRY);
            } 
            // fall through
          case 113: break;
          case 51: 
            { return token(TokenType.VOID);
            } 
            // fall through
          case 114: break;
          case 52: 
            { return token(TokenType.FOR);
            } 
            // fall through
          case 115: break;
          case 53: 
            { return token(TokenType.PUBLIC);
            } 
            // fall through
          case 116: break;
          case 54: 
            { return token(TokenType.PRINT);
            } 
            // fall through
          case 117: break;
          case 55: 
            { return token(TokenType.SWITCH);
            } 
            // fall through
          case 118: break;
          case 56: 
            { return token(TokenType.CHAR);
            } 
            // fall through
          case 119: break;
          case 57: 
            { return token(TokenType.PRIVATE);
            } 
            // fall through
          case 120: break;
          case 58: 
            { return token(TokenType.WHILE);
            } 
            // fall through
          case 121: break;
          case 59: 
            { return token(TokenType.DOUBLE);
            } 
            // fall through
          case 122: break;
          case 60: 
            { return token(TokenType.TRUE);
            } 
            // fall through
          case 123: break;
          case 61: 
            { return token(TokenType.CATCH);
            } 
            // fall through
          case 124: break;
          case 62: 
            { return token(TokenType.THROW);
            } 
            // fall through
          case 125: break;
          case 63: 
            { return token(TokenType.DEFAULT);
            } 
            // fall through
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
